import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

/**
 * Hand-written against the same conventions `components.json` already
 * declares for the shadcn CLI (cva variants, the palette from
 * MASTER_PROMPT.md §10) — see docs/modules/M13.md "Scope decisions"
 * for why this isn't generated by the CLI itself. `gold` exists but is
 * meant for exactly one thing on a screen at a time — §10: "if more
 * than one thing on a screen is gold, nothing is."
 */
const badgeVariants = cva(
  "inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium",
  {
    variants: {
      variant: {
        neutral: "bg-tint text-ink",
        deep: "bg-deep text-white",
        gold: "bg-gold text-white",
        danger: "bg-danger text-white",
        ok: "bg-ok text-white",
      },
    },
    defaultVariants: { variant: "neutral" },
  },
);

export function Badge({
  className,
  variant,
  ...props
}: React.HTMLAttributes<HTMLSpanElement> & VariantProps<typeof badgeVariants>) {
  return <span className={cn(badgeVariants({ variant }), className)} {...props} />;
}
